version: "3"

services:

  base:
    build:
      context: base/$OSNAME
    image: evernym/base:${BASE_DOCKER_TAG_PREFIX:-}$OSNAME

  rust:
    build:
      context: rust/$OSNAME
      args:
          - RUST_VERSION
    image: evernym/rust:${RUST_DOCKER_TAG_PREFIX:-}$OSNAME
