version: 0.2

env:
  variables:
    # expected
    OSNAME: ""
    AWS_REGION: ""
    AWS_ACCOUNT_ID: ""
    AWS_ECR_REPO_NAME: ""
    AWS_ECR_IMAGE_TAGS: ""
    DOCKER_NAME: ""
    DOCKER_TAG: ""
    MAKE_GOAL: ""

phases:

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)

  build:
    commands:
      - echo Build started on `date`
      - printenv
      - echo Building the Docker image...
      - export PROJECT_DIR=$CODEBUILD_SRC_DIR
      - devops/shared/aws-codebuild/ecr_build.sh "$AWS_ECR_IMAGE_TAGS" "$DOCKER_NAME:$DOCKER_TAG" "make -C devops $MAKE_GOAL"
